serenity {
    take.screenshots = DISABLED
    project.name = "Pruebas E2E - Sistema de Gestion Financiera"
}

environments {
    default {
        financial.api.url = "https://financial-managment-app.onrender.com"
        income.api.url = "https://income-service-0qn4.onrender.com"
        report.api.url = "https://report-service-uks2.onrender.com"
    }
}