serenity.project.name=Sistema de Gestion Financiera - Fabrica Escuela
serenity.outputDirectory=target/site/serenity
# Esto le dice a Serenity que use los resultados de Cucumber para armar el HTML completo
serenity.test.root=com.udea.financial.e2e
# Genera el reporte compacto y el reporte HTML completo interactivo
serenity.report.accessibility=true